Repository Web3-Club/Web3wiki-Website, pull requests merged in 2023-04, with the labels that each got.

#70 feat:(Readme.md):删除LICENCE中的空格
  README.md
Labels: question

#74 feat(README.md):统一一级标题，增加 emoji 在开头
  README.md
Labels: bug

#77 feat(README.md):将捐赠中提到的ETH限制删除
  README.md
Labels: documentation

#78 feat(README.md):增加Docs项目链接
  README.md
Labels: documentation
