Repository Web3-Club/Web3wiki-Website, pull requests merged in 2023-03, with the labels that each got.

#43 将剩余的注释改回成正文，修改README的bug
  README.md
  index.html
  search/search_index.json
  sitemap.xml
  sitemap.xml.gz
  web3wiki_mkdocs/docs/index.md
  web3wiki_mkdocs/docs/区块链常识/区块链/L2区块链.md
  web3wiki_mkdocs/docs/区块链常识/区块链/基于EVM.md
  web3wiki_mkdocs/site/index.html
  web3wiki_mkdocs/site/search/search_index.json
  web3wiki_mkdocs/site/sitemap.xml
  web3wiki_mkdocs/site/sitemap.xml.gz
  web3wiki_mkdocs/site/区块链常识/区块链/L2区块链/index.html
  web3wiki_mkdocs/site/区块链常识/区块链/基于EVM/index.html
  区块链常识/区块链/L2区块链/index.html
  区块链常识/区块链/基于EVM/index.html
Labels: bug

#54 feat(Readme.md):修改赞助者图片，使用html将其加入链接跳转至abetterweb3
  README.md
Labels: bug, help wanted

#57 feat(License):增加协议
  Licence
Labels: help wanted, plan｜计划, Find a solution｜已找到解决方案

#62 fix(Dao.md):删除“more”
  web3wiki_mkdocs/docs/Dapp/适用性/DAO.md
Labels: Find a solution｜已找到解决方案
